import CoreImage
import Foundation

/**
 The load-bearing test for visual card scanning.

 The API describes every catalog image with `describeCardPixels` in TypeScript, over
 sharp. This app describes the camera's view of a real card with `describeCard` in
 Swift, over CoreImage. Nothing ever compares a descriptor against another from its own
 runtime, so if the two implementations drift apart the scanner does not get worse, it
 stops working — and it does so silently, with plausible-looking low scores.

 The fixture is generated by `apps/api/scripts/write-art-parity-fixture.ts` immediately
 before this runs, so the golden values always come from the code that really builds
 the index.
 */
@main
struct DescriptorParityTests {
  struct Golden: Decodable {
    let version: Int
    let width: Int
    let height: Int
    let referenceKey: String
    let decoyKey: String
    let vector: [Int]
    let bits: [Int]
    let decoyVector: [Int]
    let decoyBits: [Int]
  }

  static func main() throws {
    guard let directory = CommandLine.arguments.dropFirst().first else {
      fatalError("Usage: descriptor-parity-tests <fixtureDir>")
    }
    let base = URL(fileURLWithPath: directory, isDirectory: true)

    let golden = try JSONDecoder().decode(
      Golden.self, from: Data(contentsOf: base.appendingPathComponent("reference-descriptor.json")))

    precondition(
      golden.version == ArtDescriptor.version,
      "Fixture is descriptor version \(golden.version), this binary is \(ArtDescriptor.version)")
    precondition(golden.width == ArtDescriptor.width && golden.height == ArtDescriptor.height)
    precondition(golden.vector.count == ArtDescriptor.dimension)
    precondition(golden.bits.count == ArtDescriptor.bitBytes)

    try checkParity(base: base, golden: golden)
    try checkIndexSearch(base: base, golden: golden)

    print("Descriptor parity: CoreImage agrees with the reference implementation")
  }

  /**
   The two pipelines resample with different Lanczos implementations, so the
   descriptors are close rather than identical. The floor is far above what a
   vertically flipped face, a channel swap or a different block order would score.
   */
  static func checkParity(base: URL, golden: Golden) throws {
    let reference = try describe(base.appendingPathComponent("reference-card.png"))
    let goldenVector = golden.vector.map { Int8($0) }
    let goldenBits = golden.bits.map { UInt8($0) }

    let similarity = cosine(reference.vector, goldenVector)
    let distance = hamming(reference.bits, goldenBits)
    print(String(format: "  reference: cosine %.4f, hamming %d", similarity, distance))
    precondition(similarity >= 0.97, "Descriptors disagree: cosine \(similarity)")
    precondition(distance <= 12, "Gradient bits disagree: hamming \(distance)")

    // Guards against a test that would pass on any two images at all.
    let decoy = try describe(base.appendingPathComponent("decoy-card.png"))
    let crossed = cosine(decoy.vector, goldenVector)
    print(String(format: "  decoy against reference: cosine %.4f", crossed))
    precondition(crossed < 0.8, "Unrelated cards are not separated: cosine \(crossed)")

    let decoySimilarity = cosine(decoy.vector, golden.decoyVector.map { Int8($0) })
    precondition(decoySimilarity >= 0.97, "Decoy descriptors disagree: \(decoySimilarity)")
  }

  /** The packed index the API serves has to parse and rank here unchanged. */
  static func checkIndexSearch(base: URL, golden: Golden) throws {
    let packed = try Data(contentsOf: base.appendingPathComponent("reference-index.bin"))
    guard let index = parseArtIndex(packed) else {
      fatalError("Could not parse the packed art index")
    }
    precondition(
      index.keys == [golden.referenceKey, golden.decoyKey],
      "Index keys came back as \(index.keys)")

    // Installed through the same globals the frame thread reads, not passed directly.
    replaceArtIndex(index)
    defer { replaceArtIndex(nil) }
    guard let installed = currentArtIndex() else { fatalError("Index did not install") }

    let image = try load(base.appendingPathComponent("reference-card.png"))
    let found = matchArt(image, in: installed).matches
    guard let best = found.first else { fatalError("Search returned nothing") }
    print(String(format: "  search: %@ at %.4f, hamming %d", best.key, best.score, best.hamming))
    precondition(best.key == golden.referenceKey, "Search picked \(best.key)")
    precondition(best.score >= 0.97, "Search scored its own card at \(best.score)")
    precondition(best.hamming <= 12, "Search reported hamming \(best.hamming)")
    precondition(
      found.count == 2 && found[1].score < best.score - 0.1,
      "The decoy is not clearly behind the winner")

    // A wrong-version index must be refused outright rather than scored against.
    var wrongVersion = [UInt8](packed)
    wrongVersion[4] = UInt8(ArtDescriptor.version + 1)
    precondition(
      parseArtIndex(Data(wrongVersion)) == nil, "A future descriptor version was accepted")
    precondition(parseArtIndex(Data(packed.prefix(40))) == nil, "A truncated index was accepted")
  }

  static func load(_ url: URL) throws -> CIImage {
    guard let image = CIImage(contentsOf: url) else {
      fatalError("Could not read \(url.lastPathComponent)")
    }
    return image
  }

  static func describe(_ url: URL) throws -> CardDescriptor {
    guard let descriptor = describeCard(try load(url)) else {
      fatalError("Could not describe \(url.lastPathComponent)")
    }
    return descriptor
  }

  static func cosine(_ a: [Int8], _ b: [Int8]) -> Double {
    precondition(a.count == b.count)
    var dot = 0.0
    var left = 0.0
    var right = 0.0
    for i in 0..<a.count {
      dot += Double(a[i]) * Double(b[i])
      left += Double(a[i]) * Double(a[i])
      right += Double(b[i]) * Double(b[i])
    }
    let norm = left.squareRoot() * right.squareRoot()
    return norm == 0 ? 0 : dot / norm
  }

  static func hamming(_ a: [UInt8], _ b: [UInt8]) -> Int {
    precondition(a.count == b.count)
    var distance = 0
    for i in 0..<a.count { distance += (a[i] ^ b[i]).nonzeroBitCount }
    return distance
  }
}
